spring-boot-jjj:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 文件上传下载配置
  upload-path: D:/product_java/jjj_erp_java/uploads


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jjj_erp_java?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root

  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379

# logback.xml中有详细的日志配置
# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  file:
    path: D:/java/logs/erp